train:
  _target_: src.dataset.EpisodesDataset #RamMonitoring
  max_num_episodes: 2
  #max_ram_usage: 30G
  name: train_dataset
test:
  _target_: src.dataset.EpisodesDataset
  max_num_episodes: null
  name: test_dataset
