_target_: src.models.tokenizer.Tokenizer

vocab_size: 512
embed_dim: 512
loss_weights: [0.1, 0.3, 1.0]
encoder:
  _target_: src.models.tokenizer.Encoder
  config:
    _target_: src.models.tokenizer.EncoderDecoderConfig
    resolution: 256
    in_channels: 3
    z_channels: 512
    ch: 64
    ch_mult: [1, 2, 4, 5, 6]
    num_res_blocks: 1
    attn_resolutions: [16, 8]
    out_ch: 3
    dropout: 0.05
decoder:
  _target_: src.models.tokenizer.Decoder
  config:
    _target_: src.models.tokenizer.EncoderDecoderConfig
    resolution: ${...encoder.config.resolution}
    in_channels: ${...encoder.config.in_channels}
    z_channels: ${...encoder.config.z_channels}
    ch: 64
    ch_mult: [1, 2, 8, 12, 12]
    num_res_blocks: 1
    attn_resolutions: [16, 8]
    out_ch: ${...encoder.config.out_ch}
    dropout: 0.0
