_target_: src.models.tokenizer.Tokenizer

vocab_size: 4096
embed_dim: 256
encoder:
  _target_: src.models.tokenizer.Encoder
  config:
    _target_: src.models.tokenizer.EncoderDecoderConfig
    resolution: 256
    in_channels: 3
    z_channels: 256
    ch: 16
    ch_mult: [1, 2, 4, 4, 6, 8]
    num_res_blocks: 1
    attn_resolutions: [8, 16]
    out_ch: 3
    dropout: 0.0
decoder:
  _target_: src.models.tokenizer.Decoder
  config: ${..encoder.config}