_target_: src.models.actor_critic.ConvActorCritic
move_shot_anchors: [4, 4]
act_continuous_size: 3
act_lock: [null, null, null, 0, null, 0]  # mske move, make shot, super, gadget, move anch, shot anch
act_continuous_lock: [0, 0, -10]  # move shift, shot shift, shot strength
activation:
  _target_: torch.nn.LeakyReLU
  negative_slope: 0.15
use_original_obs: True
checkpoint_backbone: True
checkpoint_lstm: True
fp16: False  # when True consumes *more* memory (benchmarked)
