train:
  _target_: src.dataset.EpisodesDataset #RamMonitoring
  max_num_episodes: -1
  resolution: 256
  #max_ram_usage: 30G
  name: train_dataset
  lazy: True
  unlink_old: False
test:
  _target_: src.dataset.EpisodesDataset
  max_num_episodes: null
  name: test_dataset
