hydra:
  run:
    dir: ./outputs/${wandb.name}/${now:%Y-%m-%d_%H-%M-%S}

defaults:
  - _self_
  - joint@tokenizer: tokenizer
  - joint@world_model: world_model
  - actor_critic: default
  - env: default
  - datasets: default

wandb:
  mode: online
  project: iris
  entity: null
  name: "norm"
  group: null
  tags: []
  notes: "norm locked to 1, 16x16"

initialization:
  path_to_checkpoint: null

common:
  epochs: 600
  device: "cuda:0"
  do_checkpoint: True
  seed: 0
  sequence_length: ${world_model.max_blocks}
  resume: False # run prefix on bucket or False. Loads full checkpoint

training:
  epochs_per_job: 1 # number of epochs to be run per job submission
  learning_rate: 1e-4
  grad_acc_steps: 1
  tokenizer_weight: 0.25
  tokenizer:
    batch_num_samples: 4
    agc_lambda: 0.1
    max_grad_norm: 3.0
  world_model:
    batch_num_samples: 4
    agc_lambda: 0.1
    max_grad_norm: 10.0
    weight_decay: 0.0
